<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'เปิดใช้งาน',
    'Change' => 'เปลี่ยน',
    'Deleted' => 'ลบแล้ว',
    'Delete' => 'ลบ',
    'Publish Status' => 'สถานะการเผยแพร่',
    'Published/Unpublished'=> 'สถานะการเผยแพร่',
    'Published' => 'เปิด',
    'Publish' => 'เปิด',
    'Unpublish' => 'ปิด',
    'Update' => 'แก้ไข',
    'Back'=>'กลับ',
    'Save Translate' => 'บันทึกการแปล',
    'Select {label}' => 'แนบ{label}',
    'Sorry for the inconvenience!' => 'ขออภัยในความไม่สะดวก',
    'Translate to ' => 'แปลภาษา ',
    'Unpublished' => 'ไม่เผยแพร่',
    'Warning!!' => 'ข้อควรระวัง',
    'You are using an outdated version of Internet Explorer, please upgrade' => 'คุณใช้เว็บบราวเซอร์เวอร์ชันต่ำกว่ากำหนด กรุณาอัพเดทเวอร์ชัน',
    'to any of the following web browsers to access this website.' => 'โดยคุณสามารถเลือกเว็บบราวเซอร์ที่ต้องการได้จากลิงค์ด้านล่างดังต่อไปนี้',
];
