<?php
/**
 * @author: Mattakorn Limkool
 *
 */

namespace obbz\yii2\utils;


use yii\base\Component;

class Country extends Component
{
    const COUNTRY_DATA = array(
        array("name" => "Afghanistan", "code" => "AF", "phone" => "93", "symbol" => "؋", "capital" => "Kabul", "currency" => "AFN", "continent" => "Asia"),
        array("name" => "Aland Islands", "code" => "AX", "phone" => "358", "symbol" => "€", "capital" => "Mariehamn", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Albania", "code" => "AL", "phone" => "355", "symbol" => "Lek", "capital" => "Tirana", "currency" => "ALL", "continent" => "Europe"),
        array("name" => "Algeria", "code" => "DZ", "phone" => "213", "symbol" => "دج", "capital" => "Algiers", "currency" => "DZD", "continent" => "Africa"),
        array("name" => "American Samoa", "code" => "AS", "phone" => "1684", "symbol" => "$", "capital" => "Pago Pago", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Andorra", "code" => "AD", "phone" => "376", "symbol" => "€", "capital" => "Andorra la Vella", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Angola", "code" => "AO", "phone" => "244", "symbol" => "Kz", "capital" => "Luanda", "currency" => "AOA", "continent" => "Africa"),
        array("name" => "Anguilla", "code" => "AI", "phone" => "1264", "symbol" => "$", "capital" => "The Valley", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Antarctica", "code" => "AQ", "phone" => "672", "symbol" => "$", "capital" => "Antarctica", "currency" => "AAD", "continent" => "Antarctica"),
        array("name" => "Antigua and Barbuda", "code" => "AG", "phone" => "1268", "symbol" => "$", "capital" => "St. John's", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Argentina", "code" => "AR", "phone" => "54", "symbol" => "$", "capital" => "Buenos Aires", "currency" => "ARS", "continent" => "South America"),
        array("name" => "Armenia", "code" => "AM", "phone" => "374", "symbol" => "֏", "capital" => "Yerevan", "currency" => "AMD", "continent" => "Asia"),
        array("name" => "Aruba", "code" => "AW", "phone" => "297", "symbol" => "ƒ", "capital" => "Oranjestad", "currency" => "AWG", "continent" => "North America"),
        array("name" => "Australia", "code" => "AU", "phone" => "61", "symbol" => "$", "capital" => "Canberra", "currency" => "AUD", "continent" => "Oceania"),
        array("name" => "Austria", "code" => "AT", "phone" => "43", "symbol" => "€", "capital" => "Vienna", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Azerbaijan", "code" => "AZ", "phone" => "994", "symbol" => "m", "capital" => "Baku", "currency" => "AZN", "continent" => "Asia"),
        array("name" => "Bahamas", "code" => "BS", "phone" => "1242", "symbol" => "B$", "capital" => "Nassau", "currency" => "BSD", "continent" => "North America"),
        array("name" => "Bahrain", "code" => "BH", "phone" => "973", "symbol" => ".د.ب", "capital" => "Manama", "currency" => "BHD", "continent" => "Asia"),
        array("name" => "Bangladesh", "code" => "BD", "phone" => "880", "symbol" => "৳", "capital" => "Dhaka", "currency" => "BDT", "continent" => "Asia"),
        array("name" => "Barbados", "code" => "BB", "phone" => "1246", "symbol" => "Bds$", "capital" => "Bridgetown", "currency" => "BBD", "continent" => "North America"),
        array("name" => "Belarus", "code" => "BY", "phone" => "375", "symbol" => "Br", "capital" => "Minsk", "currency" => "BYN", "continent" => "Europe"),
        array("name" => "Belgium", "code" => "BE", "phone" => "32", "symbol" => "€", "capital" => "Brussels", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Belize", "code" => "BZ", "phone" => "501", "symbol" => "$", "capital" => "Belmopan", "currency" => "BZD", "continent" => "North America"),
        array("name" => "Benin", "code" => "BJ", "phone" => "229", "symbol" => "CFA", "capital" => "Porto-Novo", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Bermuda", "code" => "BM", "phone" => "1441", "symbol" => "$", "capital" => "Hamilton", "currency" => "BMD", "continent" => "North America"),
        array("name" => "Bhutan", "code" => "BT", "phone" => "975", "symbol" => "Nu.", "capital" => "Thimphu", "currency" => "BTN", "continent" => "Asia"),
        array("name" => "Bolivia", "code" => "BO", "phone" => "591", "symbol" => "Bs.", "capital" => "Sucre", "currency" => "BOB", "continent" => "South America"),
        array("name" => "Bonaire, Sint Eustatius and Saba", "code" => "BQ", "phone" => "599", "symbol" => "$", "capital" => "Kralendijk", "currency" => "USD", "continent" => "North America"),
        array("name" => "Bosnia and Herzegovina", "code" => "BA", "phone" => "387", "symbol" => "KM", "capital" => "Sarajevo", "currency" => "BAM", "continent" => "Europe"),
        array("name" => "Botswana", "code" => "BW", "phone" => "267", "symbol" => "P", "capital" => "Gaborone", "currency" => "BWP", "continent" => "Africa"),
        array("name" => "Bouvet Island", "code" => "BV", "phone" => "55", "symbol" => "kr", "capital" => "", "currency" => "NOK", "continent" => "Antarctica"),
        array("name" => "Brazil", "code" => "BR", "phone" => "55", "symbol" => "R$", "capital" => "Brasilia", "currency" => "BRL", "continent" => "South America"),
        array("name" => "British Indian Ocean Territory", "code" => "IO", "phone" => "246", "symbol" => "$", "capital" => "Diego Garcia", "currency" => "USD", "continent" => "Asia"),
        array("name" => "Brunei Darussalam", "code" => "BN", "phone" => "673", "symbol" => "B$", "capital" => "Bandar Seri Begawan", "currency" => "BND", "continent" => "Asia"),
        array("name" => "Bulgaria", "code" => "BG", "phone" => "359", "symbol" => "Лв.", "capital" => "Sofia", "currency" => "BGN", "continent" => "Europe"),
        array("name" => "Burkina Faso", "code" => "BF", "phone" => "226", "symbol" => "CFA", "capital" => "Ouagadougou", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Burundi", "code" => "BI", "phone" => "257", "symbol" => "FBu", "capital" => "Bujumbura", "currency" => "BIF", "continent" => "Africa"),
        array("name" => "Cambodia", "code" => "KH", "phone" => "855", "symbol" => "KHR", "capital" => "Phnom Penh", "currency" => "KHR", "continent" => "Asia"),
        array("name" => "Cameroon", "code" => "CM", "phone" => "237", "symbol" => "FCFA", "capital" => "Yaounde", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Canada", "code" => "CA", "phone" => "1", "symbol" => "$", "capital" => "Ottawa", "currency" => "CAD", "continent" => "North America"),
        array("name" => "Cape Verde", "code" => "CV", "phone" => "238", "symbol" => "$", "capital" => "Praia", "currency" => "CVE", "continent" => "Africa"),
        array("name" => "Cayman Islands", "code" => "KY", "phone" => "1345", "symbol" => "$", "capital" => "George Town", "currency" => "KYD", "continent" => "North America"),
        array("name" => "Central African Republic", "code" => "CF", "phone" => "236", "symbol" => "FCFA", "capital" => "Bangui", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Chad", "code" => "TD", "phone" => "235", "symbol" => "FCFA", "capital" => "N'Djamena", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Chile", "code" => "CL", "phone" => "56", "symbol" => "$", "capital" => "Santiago", "currency" => "CLP", "continent" => "South America"),
        array("name" => "China", "code" => "CN", "phone" => "86", "symbol" => "¥", "capital" => "Beijing", "currency" => "CNY", "continent" => "Asia"),
        array("name" => "Christmas Island", "code" => "CX", "phone" => "61", "symbol" => "$", "capital" => "Flying Fish Cove", "currency" => "AUD", "continent" => "Asia"),
        array("name" => "Cocos (Keeling) Islands", "code" => "CC", "phone" => "672", "symbol" => "$", "capital" => "West Island", "currency" => "AUD", "continent" => "Asia"),
        array("name" => "Colombia", "code" => "CO", "phone" => "57", "symbol" => "$", "capital" => "Bogota", "currency" => "COP", "continent" => "South America"),
        array("name" => "Comoros", "code" => "KM", "phone" => "269", "symbol" => "CF", "capital" => "Moroni", "currency" => "KMF", "continent" => "Africa"),
        array("name" => "Congo", "code" => "CG", "phone" => "242", "symbol" => "FC", "capital" => "Brazzaville", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Congo, Democratic Republic of the Congo", "code" => "CD", "phone" => "242", "symbol" => "FC", "capital" => "Kinshasa", "currency" => "CDF", "continent" => "Africa"),
        array("name" => "Cook Islands", "code" => "CK", "phone" => "682", "symbol" => "$", "capital" => "Avarua", "currency" => "NZD", "continent" => "Oceania"),
        array("name" => "Costa Rica", "code" => "CR", "phone" => "506", "symbol" => "₡", "capital" => "San Jose", "currency" => "CRC", "continent" => "North America"),
        array("name" => "Cote D'Ivoire", "code" => "CI", "phone" => "225", "symbol" => "CFA", "capital" => "Yamoussoukro", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Croatia", "code" => "HR", "phone" => "385", "symbol" => "kn", "capital" => "Zagreb", "currency" => "HRK", "continent" => "Europe"),
        array("name" => "Cuba", "code" => "CU", "phone" => "53", "symbol" => "$", "capital" => "Havana", "currency" => "CUP", "continent" => "North America"),
        array("name" => "Curacao", "code" => "CW", "phone" => "599", "symbol" => "ƒ", "capital" => "Willemstad", "currency" => "ANG", "continent" => "North America"),
        array("name" => "Cyprus", "code" => "CY", "phone" => "357", "symbol" => "€", "capital" => "Nicosia", "currency" => "EUR", "continent" => "Asia"),
        array("name" => "Czech Republic", "code" => "CZ", "phone" => "420", "symbol" => "Kč", "capital" => "Prague", "currency" => "CZK", "continent" => "Europe"),
        array("name" => "Denmark", "code" => "DK", "phone" => "45", "symbol" => "Kr.", "capital" => "Copenhagen", "currency" => "DKK", "continent" => "Europe"),
        array("name" => "Djibouti", "code" => "DJ", "phone" => "253", "symbol" => "Fdj", "capital" => "Djibouti", "currency" => "DJF", "continent" => "Africa"),
        array("name" => "Dominica", "code" => "DM", "phone" => "1767", "symbol" => "$", "capital" => "Roseau", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Dominican Republic", "code" => "DO", "phone" => "1809", "symbol" => "$", "capital" => "Santo Domingo", "currency" => "DOP", "continent" => "North America"),
        array("name" => "Ecuador", "code" => "EC", "phone" => "593", "symbol" => "$", "capital" => "Quito", "currency" => "USD", "continent" => "South America"),
        array("name" => "Egypt", "code" => "EG", "phone" => "20", "symbol" => "ج.م", "capital" => "Cairo", "currency" => "EGP", "continent" => "Africa"),
        array("name" => "El Salvador", "code" => "SV", "phone" => "503", "symbol" => "$", "capital" => "San Salvador", "currency" => "USD", "continent" => "North America"),
        array("name" => "Equatorial Guinea", "code" => "GQ", "phone" => "240", "symbol" => "FCFA", "capital" => "Malabo", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Eritrea", "code" => "ER", "phone" => "291", "symbol" => "Nfk", "capital" => "Asmara", "currency" => "ERN", "continent" => "Africa"),
        array("name" => "Estonia", "code" => "EE", "phone" => "372", "symbol" => "€", "capital" => "Tallinn", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Ethiopia", "code" => "ET", "phone" => "251", "symbol" => "Nkf", "capital" => "Addis Ababa", "currency" => "ETB", "continent" => "Africa"),
        array("name" => "Falkland Islands (Malvinas)", "code" => "FK", "phone" => "500", "symbol" => "£", "capital" => "Stanley", "currency" => "FKP", "continent" => "South America"),
        array("name" => "Faroe Islands", "code" => "FO", "phone" => "298", "symbol" => "Kr.", "capital" => "Torshavn", "currency" => "DKK", "continent" => "Europe"),
        array("name" => "Fiji", "code" => "FJ", "phone" => "679", "symbol" => "FJ$", "capital" => "Suva", "currency" => "FJD", "continent" => "Oceania"),
        array("name" => "Finland", "code" => "FI", "phone" => "358", "symbol" => "€", "capital" => "Helsinki", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "France", "code" => "FR", "phone" => "33", "symbol" => "€", "capital" => "Paris", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "French Guiana", "code" => "GF", "phone" => "594", "symbol" => "€", "capital" => "Cayenne", "currency" => "EUR", "continent" => "South America"),
        array("name" => "French Polynesia", "code" => "PF", "phone" => "689", "symbol" => "₣", "capital" => "Papeete", "currency" => "XPF", "continent" => "Oceania"),
        array("name" => "French Southern Territories", "code" => "TF", "phone" => "262", "symbol" => "€", "capital" => "Port-aux-Francais", "currency" => "EUR", "continent" => "Antarctica"),
        array("name" => "Gabon", "code" => "GA", "phone" => "241", "symbol" => "FCFA", "capital" => "Libreville", "currency" => "XAF", "continent" => "Africa"),
        array("name" => "Gambia", "code" => "GM", "phone" => "220", "symbol" => "D", "capital" => "Banjul", "currency" => "GMD", "continent" => "Africa"),
        array("name" => "Georgia", "code" => "GE", "phone" => "995", "symbol" => "ლ", "capital" => "Tbilisi", "currency" => "GEL", "continent" => "Asia"),
        array("name" => "Germany", "code" => "DE", "phone" => "49", "symbol" => "€", "capital" => "Berlin", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Ghana", "code" => "GH", "phone" => "233", "symbol" => "GH₵", "capital" => "Accra", "currency" => "GHS", "continent" => "Africa"),
        array("name" => "Gibraltar", "code" => "GI", "phone" => "350", "symbol" => "£", "capital" => "Gibraltar", "currency" => "GIP", "continent" => "Europe"),
        array("name" => "Greece", "code" => "GR", "phone" => "30", "symbol" => "€", "capital" => "Athens", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Greenland", "code" => "GL", "phone" => "299", "symbol" => "Kr.", "capital" => "Nuuk", "currency" => "DKK", "continent" => "North America"),
        array("name" => "Grenada", "code" => "GD", "phone" => "1473", "symbol" => "$", "capital" => "St. George's", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Guadeloupe", "code" => "GP", "phone" => "590", "symbol" => "€", "capital" => "Basse-Terre", "currency" => "EUR", "continent" => "North America"),
        array("name" => "Guam", "code" => "GU", "phone" => "1671", "symbol" => "$", "capital" => "Hagatna", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Guatemala", "code" => "GT", "phone" => "502", "symbol" => "Q", "capital" => "Guatemala City", "currency" => "GTQ", "continent" => "North America"),
        array("name" => "Guernsey", "code" => "GG", "phone" => "44", "symbol" => "£", "capital" => "St Peter Port", "currency" => "GBP", "continent" => "Europe"),
        array("name" => "Guinea", "code" => "GN", "phone" => "224", "symbol" => "FG", "capital" => "Conakry", "currency" => "GNF", "continent" => "Africa"),
        array("name" => "Guinea-Bissau", "code" => "GW", "phone" => "245", "symbol" => "CFA", "capital" => "Bissau", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Guyana", "code" => "GY", "phone" => "592", "symbol" => "$", "capital" => "Georgetown", "currency" => "GYD", "continent" => "South America"),
        array("name" => "Haiti", "code" => "HT", "phone" => "509", "symbol" => "G", "capital" => "Port-au-Prince", "currency" => "HTG", "continent" => "North America"),
        array("name" => "Heard Island and McDonald Islands", "code" => "HM", "phone" => "0", "symbol" => "$", "capital" => "", "currency" => "AUD", "continent" => "Antarctica"),
        array("name" => "Holy See (Vatican City State)", "code" => "VA", "phone" => "39", "symbol" => "€", "capital" => "Vatican City", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Honduras", "code" => "HN", "phone" => "504", "symbol" => "L", "capital" => "Tegucigalpa", "currency" => "HNL", "continent" => "North America"),
        array("name" => "Hong Kong", "code" => "HK", "phone" => "852", "symbol" => "$", "capital" => "Hong Kong", "currency" => "HKD", "continent" => "Asia"),
        array("name" => "Hungary", "code" => "HU", "phone" => "36", "symbol" => "Ft", "capital" => "Budapest", "currency" => "HUF", "continent" => "Europe"),
        array("name" => "Iceland", "code" => "IS", "phone" => "354", "symbol" => "kr", "capital" => "Reykjavik", "currency" => "ISK", "continent" => "Europe"),
        array("name" => "India", "code" => "IN", "phone" => "91", "symbol" => "₹", "capital" => "New Delhi", "currency" => "INR", "continent" => "Asia"),
        array("name" => "Indonesia", "code" => "ID", "phone" => "62", "symbol" => "Rp", "capital" => "Jakarta", "currency" => "IDR", "continent" => "Asia"),
        array("name" => "Iran, Islamic Republic of", "code" => "IR", "phone" => "98", "symbol" => "﷼", "capital" => "Tehran", "currency" => "IRR", "continent" => "Asia"),
        array("name" => "Iraq", "code" => "IQ", "phone" => "964", "symbol" => "د.ع", "capital" => "Baghdad", "currency" => "IQD", "continent" => "Asia"),
        array("name" => "Ireland", "code" => "IE", "phone" => "353", "symbol" => "€", "capital" => "Dublin", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Isle of Man", "code" => "IM", "phone" => "44", "symbol" => "£", "capital" => "Douglas, Isle of Man", "currency" => "GBP", "continent" => "Europe"),
        array("name" => "Israel", "code" => "IL", "phone" => "972", "symbol" => "₪", "capital" => "Jerusalem", "currency" => "ILS", "continent" => "Asia"),
        array("name" => "Italy", "code" => "IT", "phone" => "39", "symbol" => "€", "capital" => "Rome", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Jamaica", "code" => "JM", "phone" => "1876", "symbol" => "J$", "capital" => "Kingston", "currency" => "JMD", "continent" => "North America"),
        array("name" => "Japan", "code" => "JP", "phone" => "81", "symbol" => "¥", "capital" => "Tokyo", "currency" => "JPY", "continent" => "Asia"),
        array("name" => "Jersey", "code" => "JE", "phone" => "44", "symbol" => "£", "capital" => "Saint Helier", "currency" => "GBP", "continent" => "Europe"),
        array("name" => "Jordan", "code" => "JO", "phone" => "962", "symbol" => "ا.د", "capital" => "Amman", "currency" => "JOD", "continent" => "Asia"),
        array("name" => "Kazakhstan", "code" => "KZ", "phone" => "7", "symbol" => "лв", "capital" => "Astana", "currency" => "KZT", "continent" => "Asia"),
        array("name" => "Kenya", "code" => "KE", "phone" => "254", "symbol" => "KSh", "capital" => "Nairobi", "currency" => "KES", "continent" => "Africa"),
        array("name" => "Kiribati", "code" => "KI", "phone" => "686", "symbol" => "$", "capital" => "Tarawa", "currency" => "AUD", "continent" => "Oceania"),
        array("name" => "Korea, Democratic People's Republic of", "code" => "KP", "phone" => "850", "symbol" => "₩", "capital" => "Pyongyang", "currency" => "KPW", "continent" => "Asia"),
        array("name" => "Korea, Republic of", "code" => "KR", "phone" => "82", "symbol" => "₩", "capital" => "Seoul", "currency" => "KRW", "continent" => "Asia"),
        array("name" => "Kosovo", "code" => "XK", "phone" => "381", "symbol" => "€", "capital" => "Pristina", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Kuwait", "code" => "KW", "phone" => "965", "symbol" => "ك.د", "capital" => "Kuwait City", "currency" => "KWD", "continent" => "Asia"),
        array("name" => "Kyrgyzstan", "code" => "KG", "phone" => "996", "symbol" => "лв", "capital" => "Bishkek", "currency" => "KGS", "continent" => "Asia"),
        array("name" => "Lao People's Democratic Republic", "code" => "LA", "phone" => "856", "symbol" => "₭", "capital" => "Vientiane", "currency" => "LAK", "continent" => "Asia"),
        array("name" => "Latvia", "code" => "LV", "phone" => "371", "symbol" => "€", "capital" => "Riga", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Lebanon", "code" => "LB", "phone" => "961", "symbol" => "£", "capital" => "Beirut", "currency" => "LBP", "continent" => "Asia"),
        array("name" => "Lesotho", "code" => "LS", "phone" => "266", "symbol" => "L", "capital" => "Maseru", "currency" => "LSL", "continent" => "Africa"),
        array("name" => "Liberia", "code" => "LR", "phone" => "231", "symbol" => "$", "capital" => "Monrovia", "currency" => "LRD", "continent" => "Africa"),
        array("name" => "Libyan Arab Jamahiriya", "code" => "LY", "phone" => "218", "symbol" => "د.ل", "capital" => "Tripolis", "currency" => "LYD", "continent" => "Africa"),
        array("name" => "Liechtenstein", "code" => "LI", "phone" => "423", "symbol" => "CHf", "capital" => "Vaduz", "currency" => "CHF", "continent" => "Europe"),
        array("name" => "Lithuania", "code" => "LT", "phone" => "370", "symbol" => "€", "capital" => "Vilnius", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Luxembourg", "code" => "LU", "phone" => "352", "symbol" => "€", "capital" => "Luxembourg", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Macao", "code" => "MO", "phone" => "853", "symbol" => "$", "capital" => "Macao", "currency" => "MOP", "continent" => "Asia"),
        array("name" => "Macedonia, the Former Yugoslav Republic of", "code" => "MK", "phone" => "389", "symbol" => "ден", "capital" => "Skopje", "currency" => "MKD", "continent" => "Europe"),
        array("name" => "Madagascar", "code" => "MG", "phone" => "261", "symbol" => "Ar", "capital" => "Antananarivo", "currency" => "MGA", "continent" => "Africa"),
        array("name" => "Malawi", "code" => "MW", "phone" => "265", "symbol" => "MK", "capital" => "Lilongwe", "currency" => "MWK", "continent" => "Africa"),
        array("name" => "Malaysia", "code" => "MY", "phone" => "60", "symbol" => "RM", "capital" => "Kuala Lumpur", "currency" => "MYR", "continent" => "Asia"),
        array("name" => "Maldives", "code" => "MV", "phone" => "960", "symbol" => "Rf", "capital" => "Male", "currency" => "MVR", "continent" => "Asia"),
        array("name" => "Mali", "code" => "ML", "phone" => "223", "symbol" => "CFA", "capital" => "Bamako", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Malta", "code" => "MT", "phone" => "356", "symbol" => "€", "capital" => "Valletta", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Marshall Islands", "code" => "MH", "phone" => "692", "symbol" => "$", "capital" => "Majuro", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Martinique", "code" => "MQ", "phone" => "596", "symbol" => "€", "capital" => "Fort-de-France", "currency" => "EUR", "continent" => "North America"),
        array("name" => "Mauritania", "code" => "MR", "phone" => "222", "symbol" => "MRU", "capital" => "Nouakchott", "currency" => "MRO", "continent" => "Africa"),
        array("name" => "Mauritius", "code" => "MU", "phone" => "230", "symbol" => "₨", "capital" => "Port Louis", "currency" => "MUR", "continent" => "Africa"),
        array("name" => "Mayotte", "code" => "YT", "phone" => "262", "symbol" => "€", "capital" => "Mamoudzou", "currency" => "EUR", "continent" => "Africa"),
        array("name" => "Mexico", "code" => "MX", "phone" => "52", "symbol" => "$", "capital" => "Mexico City", "currency" => "MXN", "continent" => "North America"),
        array("name" => "Micronesia, Federated States of", "code" => "FM", "phone" => "691", "symbol" => "$", "capital" => "Palikir", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Moldova, Republic of", "code" => "MD", "phone" => "373", "symbol" => "L", "capital" => "Chisinau", "currency" => "MDL", "continent" => "Europe"),
        array("name" => "Monaco", "code" => "MC", "phone" => "377", "symbol" => "€", "capital" => "Monaco", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Mongolia", "code" => "MN", "phone" => "976", "symbol" => "₮", "capital" => "Ulan Bator", "currency" => "MNT", "continent" => "Asia"),
        array("name" => "Montenegro", "code" => "ME", "phone" => "382", "symbol" => "€", "capital" => "Podgorica", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Montserrat", "code" => "MS", "phone" => "1664", "symbol" => "$", "capital" => "Plymouth", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Morocco", "code" => "MA", "phone" => "212", "symbol" => "DH", "capital" => "Rabat", "currency" => "MAD", "continent" => "Africa"),
        array("name" => "Mozambique", "code" => "MZ", "phone" => "258", "symbol" => "MT", "capital" => "Maputo", "currency" => "MZN", "continent" => "Africa"),
        array("name" => "Myanmar", "code" => "MM", "phone" => "95", "symbol" => "K", "capital" => "Nay Pyi Taw", "currency" => "MMK", "continent" => "Asia"),
        array("name" => "Namibia", "code" => "NA", "phone" => "264", "symbol" => "$", "capital" => "Windhoek", "currency" => "NAD", "continent" => "Africa"),
        array("name" => "Nauru", "code" => "NR", "phone" => "674", "symbol" => "$", "capital" => "Yaren", "currency" => "AUD", "continent" => "Oceania"),
        array("name" => "Nepal", "code" => "NP", "phone" => "977", "symbol" => "₨", "capital" => "Kathmandu", "currency" => "NPR", "continent" => "Asia"),
        array("name" => "Netherlands", "code" => "NL", "phone" => "31", "symbol" => "€", "capital" => "Amsterdam", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Netherlands Antilles", "code" => "AN", "phone" => "599", "symbol" => "NAf", "capital" => "Willemstad", "currency" => "ANG", "continent" => "North America"),
        array("name" => "New Caledonia", "code" => "NC", "phone" => "687", "symbol" => "₣", "capital" => "Noumea", "currency" => "XPF", "continent" => "Oceania"),
        array("name" => "New Zealand", "code" => "NZ", "phone" => "64", "symbol" => "$", "capital" => "Wellington", "currency" => "NZD", "continent" => "Oceania"),
        array("name" => "Nicaragua", "code" => "NI", "phone" => "505", "symbol" => "C$", "capital" => "Managua", "currency" => "NIO", "continent" => "North America"),
        array("name" => "Niger", "code" => "NE", "phone" => "227", "symbol" => "CFA", "capital" => "Niamey", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Nigeria", "code" => "NG", "phone" => "234", "symbol" => "₦", "capital" => "Abuja", "currency" => "NGN", "continent" => "Africa"),
        array("name" => "Niue", "code" => "NU", "phone" => "683", "symbol" => "$", "capital" => "Alofi", "currency" => "NZD", "continent" => "Oceania"),
        array("name" => "Norfolk Island", "code" => "NF", "phone" => "672", "symbol" => "$", "capital" => "Kingston", "currency" => "AUD", "continent" => "Oceania"),
        array("name" => "Northern Mariana Islands", "code" => "MP", "phone" => "1670", "symbol" => "$", "capital" => "Saipan", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Norway", "code" => "NO", "phone" => "47", "symbol" => "kr", "capital" => "Oslo", "currency" => "NOK", "continent" => "Europe"),
        array("name" => "Oman", "code" => "OM", "phone" => "968", "symbol" => ".ع.ر", "capital" => "Muscat", "currency" => "OMR", "continent" => "Asia"),
        array("name" => "Pakistan", "code" => "PK", "phone" => "92", "symbol" => "₨", "capital" => "Islamabad", "currency" => "PKR", "continent" => "Asia"),
        array("name" => "Palau", "code" => "PW", "phone" => "680", "symbol" => "$", "capital" => "Melekeok", "currency" => "USD", "continent" => "Oceania"),
        array("name" => "Palestinian Territory, Occupied", "code" => "PS", "phone" => "970", "symbol" => "₪", "capital" => "East Jerusalem", "currency" => "ILS", "continent" => "Asia"),
        array("name" => "Panama", "code" => "PA", "phone" => "507", "symbol" => "B/.", "capital" => "Panama City", "currency" => "PAB", "continent" => "North America"),
        array("name" => "Papua New Guinea", "code" => "PG", "phone" => "675", "symbol" => "K", "capital" => "Port Moresby", "currency" => "PGK", "continent" => "Oceania"),
        array("name" => "Paraguay", "code" => "PY", "phone" => "595", "symbol" => "₲", "capital" => "Asuncion", "currency" => "PYG", "continent" => "South America"),
        array("name" => "Peru", "code" => "PE", "phone" => "51", "symbol" => "S/.", "capital" => "Lima", "currency" => "PEN", "continent" => "South America"),
        array("name" => "Philippines", "code" => "PH", "phone" => "63", "symbol" => "₱", "capital" => "Manila", "currency" => "PHP", "continent" => "Asia"),
        array("name" => "Pitcairn", "code" => "PN", "phone" => "64", "symbol" => "$", "capital" => "Adamstown", "currency" => "NZD", "continent" => "Oceania"),
        array("name" => "Poland", "code" => "PL", "phone" => "48", "symbol" => "zł", "capital" => "Warsaw", "currency" => "PLN", "continent" => "Europe"),
        array("name" => "Portugal", "code" => "PT", "phone" => "351", "symbol" => "€", "capital" => "Lisbon", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Puerto Rico", "code" => "PR", "phone" => "1787", "symbol" => "$", "capital" => "San Juan", "currency" => "USD", "continent" => "North America"),
        array("name" => "Qatar", "code" => "QA", "phone" => "974", "symbol" => "ق.ر", "capital" => "Doha", "currency" => "QAR", "continent" => "Asia"),
        array("name" => "Reunion", "code" => "RE", "phone" => "262", "symbol" => "€", "capital" => "Saint-Denis", "currency" => "EUR", "continent" => "Africa"),
        array("name" => "Romania", "code" => "RO", "phone" => "40", "symbol" => "lei", "capital" => "Bucharest", "currency" => "RON", "continent" => "Europe"),
        array("name" => "Russian Federation", "code" => "RU", "phone" => "70", "symbol" => "₽", "capital" => "Moscow", "currency" => "RUB", "continent" => "Asia"),
        array("name" => "Rwanda", "code" => "RW", "phone" => "250", "symbol" => "FRw", "capital" => "Kigali", "currency" => "RWF", "continent" => "Africa"),
        array("name" => "Saint Barthelemy", "code" => "BL", "phone" => "590", "symbol" => "€", "capital" => "Gustavia", "currency" => "EUR", "continent" => "North America"),
        array("name" => "Saint Helena", "code" => "SH", "phone" => "290", "symbol" => "£", "capital" => "Jamestown", "currency" => "SHP", "continent" => "Africa"),
        array("name" => "Saint Kitts and Nevis", "code" => "KN", "phone" => "1869", "symbol" => "$", "capital" => "Basseterre", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Saint Lucia", "code" => "LC", "phone" => "1758", "symbol" => "$", "capital" => "Castries", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Saint Martin", "code" => "MF", "phone" => "590", "symbol" => "€", "capital" => "Marigot", "currency" => "EUR", "continent" => "North America"),
        array("name" => "Saint Pierre and Miquelon", "code" => "PM", "phone" => "508", "symbol" => "€", "capital" => "Saint-Pierre", "currency" => "EUR", "continent" => "North America"),
        array("name" => "Saint Vincent and the Grenadines", "code" => "VC", "phone" => "1784", "symbol" => "$", "capital" => "Kingstown", "currency" => "XCD", "continent" => "North America"),
        array("name" => "Samoa", "code" => "WS", "phone" => "684", "symbol" => "SAT", "capital" => "Apia", "currency" => "WST", "continent" => "Oceania"),
        array("name" => "San Marino", "code" => "SM", "phone" => "378", "symbol" => "€", "capital" => "San Marino", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Sao Tome and Principe", "code" => "ST", "phone" => "239", "symbol" => "Db", "capital" => "Sao Tome", "currency" => "STD", "continent" => "Africa"),
        array("name" => "Saudi Arabia", "code" => "SA", "phone" => "966", "symbol" => "﷼", "capital" => "Riyadh", "currency" => "SAR", "continent" => "Asia"),
        array("name" => "Senegal", "code" => "SN", "phone" => "221", "symbol" => "CFA", "capital" => "Dakar", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Serbia", "code" => "RS", "phone" => "381", "symbol" => "din", "capital" => "Belgrade", "currency" => "RSD", "continent" => "Europe"),
        array("name" => "Serbia and Montenegro", "code" => "CS", "phone" => "381", "symbol" => "din", "capital" => "Belgrade", "currency" => "RSD", "continent" => "Europe"),
        array("name" => "Seychelles", "code" => "SC", "phone" => "248", "symbol" => "SRe", "capital" => "Victoria", "currency" => "SCR", "continent" => "Africa"),
        array("name" => "Sierra Leone", "code" => "SL", "phone" => "232", "symbol" => "Le", "capital" => "Freetown", "currency" => "SLL", "continent" => "Africa"),
        array("name" => "Singapore", "code" => "SG", "phone" => "65", "symbol" => "$", "capital" => "Singapur", "currency" => "SGD", "continent" => "Asia"),
        array("name" => "St Martin", "code" => "SX", "phone" => "1", "symbol" => "ƒ", "capital" => "Philipsburg", "currency" => "ANG", "continent" => "North America"),
        array("name" => "Slovakia", "code" => "SK", "phone" => "421", "symbol" => "€", "capital" => "Bratislava", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Slovenia", "code" => "SI", "phone" => "386", "symbol" => "€", "capital" => "Ljubljana", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Solomon Islands", "code" => "SB", "phone" => "677", "symbol" => "Si$", "capital" => "Honiara", "currency" => "SBD", "continent" => "Oceania"),
        array("name" => "Somalia", "code" => "SO", "phone" => "252", "symbol" => "Sh.so.", "capital" => "Mogadishu", "currency" => "SOS", "continent" => "Africa"),
        array("name" => "South Africa", "code" => "ZA", "phone" => "27", "symbol" => "R", "capital" => "Pretoria", "currency" => "ZAR", "continent" => "Africa"),
        array("name" => "South Georgia and the South Sandwich Islands", "code" => "GS", "phone" => "500", "symbol" => "£", "capital" => "Grytviken", "currency" => "GBP", "continent" => "Antarctica"),
        array("name" => "South Sudan", "code" => "SS", "phone" => "211", "symbol" => "£", "capital" => "Juba", "currency" => "SSP", "continent" => "Africa"),
        array("name" => "Spain", "code" => "ES", "phone" => "34", "symbol" => "€", "capital" => "Madrid", "currency" => "EUR", "continent" => "Europe"),
        array("name" => "Sri Lanka", "code" => "LK", "phone" => "94", "symbol" => "Rs", "capital" => "Colombo", "currency" => "LKR", "continent" => "Asia"),
        array("name" => "Sudan", "code" => "SD", "phone" => "249", "symbol" => ".س.ج", "capital" => "Khartoum", "currency" => "SDG", "continent" => "Africa"),
        array("name" => "Suriname", "code" => "SR", "phone" => "597", "symbol" => "$", "capital" => "Paramaribo", "currency" => "SRD", "continent" => "South America"),
        array("name" => "Svalbard and Jan Mayen", "code" => "SJ", "phone" => "47", "symbol" => "kr", "capital" => "Longyearbyen", "currency" => "NOK", "continent" => "Europe"),
        array("name" => "Swaziland", "code" => "SZ", "phone" => "268", "symbol" => "E", "capital" => "Mbabane", "currency" => "SZL", "continent" => "Africa"),
        array("name" => "Sweden", "code" => "SE", "phone" => "46", "symbol" => "kr", "capital" => "Stockholm", "currency" => "SEK", "continent" => "Europe"),
        array("name" => "Switzerland", "code" => "CH", "phone" => "41", "symbol" => "CHf", "capital" => "Berne", "currency" => "CHF", "continent" => "Europe"),
        array("name" => "Syrian Arab Republic", "code" => "SY", "phone" => "963", "symbol" => "LS", "capital" => "Damascus", "currency" => "SYP", "continent" => "Asia"),
        array("name" => "Taiwan, Province of China", "code" => "TW", "phone" => "886", "symbol" => "$", "capital" => "Taipei", "currency" => "TWD", "continent" => "Asia"),
        array("name" => "Tajikistan", "code" => "TJ", "phone" => "992", "symbol" => "SM", "capital" => "Dushanbe", "currency" => "TJS", "continent" => "Asia"),
        array("name" => "Tanzania, United Republic of", "code" => "TZ", "phone" => "255", "symbol" => "TSh", "capital" => "Dodoma", "currency" => "TZS", "continent" => "Africa"),
        array("name" => "Thailand", "code" => "TH", "phone" => "66", "symbol" => "฿", "capital" => "Bangkok", "currency" => "THB", "continent" => "Asia"),
        array("name" => "Timor-Leste", "code" => "TL", "phone" => "670", "symbol" => "$", "capital" => "Dili", "currency" => "USD", "continent" => "Asia"),
        array("name" => "Togo", "code" => "TG", "phone" => "228", "symbol" => "CFA", "capital" => "Lome", "currency" => "XOF", "continent" => "Africa"),
        array("name" => "Tokelau", "code" => "TK", "phone" => "690", "symbol" => "$", "capital" => "", "currency" => "NZD", "continent" => "Oceania"),
        array("name" => "Tonga", "code" => "TO", "phone" => "676", "symbol" => "$", "capital" => "Nuku'alofa", "currency" => "TOP", "continent" => "Oceania"),
        array("name" => "Trinidad and Tobago", "code" => "TT", "phone" => "1868", "symbol" => "$", "capital" => "Port of Spain", "currency" => "TTD", "continent" => "North America"),
        array("name" => "Tunisia", "code" => "TN", "phone" => "216", "symbol" => "ت.د", "capital" => "Tunis", "currency" => "TND", "continent" => "Africa"),
        array("name" => "Turkey", "code" => "TR", "phone" => "90", "symbol" => "₺", "capital" => "Ankara", "currency" => "TRY", "continent" => "Asia"),
        array("name" => "Turkmenistan", "code" => "TM", "phone" => "7370", "symbol" => "T", "capital" => "Ashgabat", "currency" => "TMT", "continent" => "Asia"),
        array("name" => "Turks and Caicos Islands", "code" => "TC", "phone" => "1649", "symbol" => "$", "capital" => "Cockburn Town", "currency" => "USD", "continent" => "North America"),
        array("name" => "Tuvalu", "code" => "TV", "phone" => "688", "symbol" => "$", "capital" => "Funafuti", "currency" => "AUD", "continent" => "Oceania"),
        array("name" => "Uganda", "code" => "UG", "phone" => "256", "symbol" => "USh", "capital" => "Kampala", "currency" => "UGX", "continent" => "Africa"),
        array("name" => "Ukraine", "code" => "UA", "phone" => "380", "symbol" => "₴", "capital" => "Kiev", "currency" => "UAH", "continent" => "Europe"),
        array("name" => "United Arab Emirates", "code" => "AE", "phone" => "971", "symbol" => "إ.د", "capital" => "Abu Dhabi", "currency" => "AED", "continent" => "Asia"),
        array("name" => "United Kingdom", "code" => "GB", "phone" => "44", "symbol" => "£", "capital" => "London", "currency" => "GBP", "continent" => "Europe"),
        array("name" => "United States", "code" => "US", "phone" => "1", "symbol" => "$", "capital" => "Washington", "currency" => "USD", "continent" => "North America"),
        array("name" => "United States Minor Outlying Islands", "code" => "UM", "phone" => "1", "symbol" => "$", "capital" => "", "currency" => "USD", "continent" => "North America"),
        array("name" => "Uruguay", "code" => "UY", "phone" => "598", "symbol" => "$", "capital" => "Montevideo", "currency" => "UYU", "continent" => "South America"),
        array("name" => "Uzbekistan", "code" => "UZ", "phone" => "998", "symbol" => "лв", "capital" => "Tashkent", "currency" => "UZS", "continent" => "Asia"),
        array("name" => "Vanuatu", "code" => "VU", "phone" => "678", "symbol" => "VT", "capital" => "Port Vila", "currency" => "VUV", "continent" => "Oceania"),
        array("name" => "Venezuela", "code" => "VE", "phone" => "58", "symbol" => "Bs", "capital" => "Caracas", "currency" => "VEF", "continent" => "South America"),
        array("name" => "Viet Nam", "code" => "VN", "phone" => "84", "symbol" => "₫", "capital" => "Hanoi", "currency" => "VND", "continent" => "Asia"),
        array("name" => "Virgin Islands, British", "code" => "VG", "phone" => "1284", "symbol" => "$", "capital" => "Road Town", "currency" => "USD", "continent" => "North America"),
        array("name" => "Virgin Islands, U.s.", "code" => "VI", "phone" => "1340", "symbol" => "$", "capital" => "Charlotte Amalie", "currency" => "USD", "continent" => "North America"),
        array("name" => "Wallis and Futuna", "code" => "WF", "phone" => "681", "symbol" => "₣", "capital" => "Mata Utu", "currency" => "XPF", "continent" => "Oceania"),
        array("name" => "Western Sahara", "code" => "EH", "phone" => "212", "symbol" => "MAD", "capital" => "El-Aaiun", "currency" => "MAD", "continent" => "Africa"),
        array("name" => "Yemen", "code" => "YE", "phone" => "967", "symbol" => "﷼", "capital" => "Sanaa", "currency" => "YER", "continent" => "Asia"),
        array("name" => "Zambia", "code" => "ZM", "phone" => "260", "symbol" => "ZK", "capital" => "Lusaka", "currency" => "ZMW", "continent" => "Africa"),
        array("name" => "Zimbabwe", "code" => "ZW", "phone" => "263", "symbol" => "$", "capital" => "Harare", "currency" => "ZWL", "continent" => "Africa")
    );

    public static function getList(){
        return ArrayHelper::map(self::COUNTRY_DATA, 'code', 'name');
    }

}